name: Run Linters

on:
  workflow_call:

jobs:
  linters:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ hashFiles('dependencies.sh') }}
      - name: Install tools
        run: |
          pip3 install setuptools
          bash tools/ci/install_spaceman_dmm.sh dreamchecker
          bash tools/ci/install_ripgrep.sh
          tools/bootstrap/python -c ''
      - name: Check project files and maps
        run: |
          bash tools/ci/check_filedirs.sh roguetown.dme
          bash tools/ci/check_changelogs.sh
          find . -name '*.php' -print0 | xargs -0 -r -n1 php -l
          tools/bootstrap/python -m dmi.test
          tools/bootstrap/python -m mapmerge2.dmm_test
      - name: Run DreamChecker
        run: ~/dreamchecker > output-annotations.txt 2>&1
      - name: Annotate DreamChecker
        uses: yogstation13/DreamAnnotate@v2
        if: always()
        with:
          outputFile: output-annotations.txt
      - name: Run grep checks
        if: '!cancelled()'
        run: bash tools/ci/check_grep.sh
